export const UI = {
  "zh-TW": {
    contact: "聯絡方式", websites: "網站", pending: "準備中", skip: "跳至主要內容", notFound: "找不到頁面", back: "返回首頁", language: "語言", appearance: "外觀", preferences: "網站外觀", credit: "由", creditEnd: "製作", visitor: "位來訪者",
    admin: {
      title: "管理後台", description: "個人聯絡頁管理後台", content: "內容管理", menu: "管理選單", profile: "個人資料", bio: "個人簡介", links: "聯絡連結", settings: "網站設定", viewSite: "查看網站", logout: "登出", save: "儲存變更",
      profileHelp: "設定公開顯示的身份與狀態。", name: "名稱", avatar: "頭像", avatarHelp: "上傳 JPG、PNG 或 WebP；會自動裁切及壓縮。", chooseImage: "選擇圖片", remove: "移除", imageUrl: "圖片網址（選填）", imageUrlHelp: "可上傳圖片或填寫 http(s) 圖片網址；留空會顯示名稱縮寫。", currentAvatar: "目前頭像", status: "狀態",
      bioHelp: "可為三種訪客語言分別撰寫簡介。", linksHelp: "調整聯絡方式、顯示狀態與順序。", addWebsite: "新增網站", addContact: "新增聯絡方式", addEmail: "新增電子郵件", siteList: "網站列表", contactList: "聯絡方式", displayName: "顯示名稱", emailAddress: "電子郵件地址", accountText: "帳號／顯示文字", url: "網址", icon: "簡筆圖", show: "顯示", delete: "刪除", deleteItem: "刪除這個項目", moveUp: "向上移動", moveDown: "向下移動", order: "順序", unnamed: "未命名", newLink: "新連結", customUrl: "自訂網址", maximumLinks: "聯絡連結最多 20 項",
      settingsHelp: "管理網頁標題、網址與登入安全。", siteTitle: "瀏覽器分頁標題", siteTitleHint: "留空則使用個人資料的名稱；修改後按「儲存變更」。", canonical: "網站公開網址", canonicalHint: "供搜尋引擎與分享預覽辨識本站；留空則使用目前網域。", footerLink: "頁尾連結", footerHelp: "名稱或網址留空則不顯示連結。", changePassword: "修改密碼", passwordHelp: "修改後所有已登入裝置都需要重新登入。", currentPassword: "目前密碼", newPassword: "新密碼", confirmPassword: "確認新密碼", updatePassword: "更新密碼", updating: "更新中…", passwordMismatch: "兩次輸入的新密碼不同", passwordUpdated: "密碼已更新，請重新登入", passwordUpdateFailed: "密碼更新失敗", saved: "已儲存", saveFailed: "儲存失敗", imageType: "只支援 JPG、PNG 或 WebP", imageFailed: "無法處理圖片", imageUnreadable: "圖片無法讀取", imageTooLarge: "圖片壓縮後仍過大，請選擇較簡單的圖片", imageConvertFailed: "圖片轉換失敗",
      loginPrompt: "輸入管理密碼。", password: "密碼", signIn: "登入", backToSite: "返回聯絡頁", forbidden: "禁止存取", forbiddenDetail: "管理工作階段無效，請重新登入。", goToLogin: "前往登入"
    },
    api: { unauthorized: "未獲授權", invalidOrigin: "無法驗證請求來源", jsonRequired: "需要 JSON 格式", bodyTooLarge: "請求內容過大", invalidJson: "JSON 格式錯誤", validationFailed: "設定驗證失敗", notFound: "找不到資源", serverError: "伺服器錯誤", newPasswordEmpty: "新密碼不可為空", currentPasswordWrong: "目前密碼錯誤", loginOrigin: "無法驗證登入來源，請重新整理後再試。", loginTooLarge: "登入資料過大。", loginFormat: "登入格式錯誤。", passwordWrong: "密碼錯誤。" },
    icons: { globe: "網站", link: "連結", home: "首頁", blog: "文章", rss: "RSS", code: "程式碼", book: "書籍", briefcase: "工作", store: "商店", chain: "鏈上", email: "郵件", phone: "電話", message: "訊息", calendar: "日曆", map: "地圖", camera: "相機", cloud: "雲端" }
  },
  en: {
    contact: "Contact", websites: "Websites", pending: "Coming soon", skip: "Skip to content", notFound: "Page not found", back: "Back home", language: "Language", appearance: "Appearance", preferences: "Site appearance", credit: "Powered by", creditEnd: "", visitor: "Visitor #",
    admin: {
      title: "Admin", description: "Contact Hub administration", content: "Content", menu: "Admin navigation", profile: "Profile", bio: "Bio", links: "Contact links", settings: "Site settings", viewSite: "View site", logout: "Log out", save: "Save changes",
      profileHelp: "Set your public identity and status.", name: "Name", avatar: "Avatar", avatarHelp: "Upload JPG, PNG, or WebP; the image is cropped and compressed automatically.", chooseImage: "Choose image", remove: "Remove", imageUrl: "Image URL (optional)", imageUrlHelp: "Upload an image or enter an http(s) image URL. Leave blank to show your initials.", currentAvatar: "Current avatar", status: "Status",
      bioHelp: "Write a bio for each visitor language.", linksHelp: "Edit contact methods, visibility, and order.", addWebsite: "Add website", addContact: "Add contact", addEmail: "Add email", siteList: "Websites", contactList: "Contact methods", displayName: "Display name", emailAddress: "Email address", accountText: "Account / display text", url: "URL", icon: "Icon", show: "Show", delete: "Delete", deleteItem: "Delete this item", moveUp: "Move up", moveDown: "Move down", order: "Order", unnamed: "Untitled", newLink: "New link", customUrl: "Custom URL", maximumLinks: "Up to 20 contact links are allowed",
      settingsHelp: "Manage the page title, URL, and sign-in security.", siteTitle: "Browser tab title", siteTitleHint: "Leave blank to use your profile name; then select Save changes.", canonical: "Public site URL", canonicalHint: "Used for search and sharing. Leave blank to use the current domain.", footerLink: "Footer link", footerHelp: "Leave the name or URL blank to hide the link.", changePassword: "Change password", passwordHelp: "Changing it signs out all existing sessions.", currentPassword: "Current password", newPassword: "New password", confirmPassword: "Confirm new password", updatePassword: "Update password", updating: "Updating…", passwordMismatch: "The new passwords do not match", passwordUpdated: "Password updated. Please sign in again.", passwordUpdateFailed: "Could not update password", saved: "Saved", saveFailed: "Could not save", imageType: "Only JPG, PNG, and WebP are supported", imageFailed: "Could not process image", imageUnreadable: "Could not read image", imageTooLarge: "Image is still too large after compression. Try a simpler image.", imageConvertFailed: "Could not convert image",
      loginPrompt: "Enter your admin password.", password: "Password", signIn: "Sign in", backToSite: "Back to contact page", forbidden: "Access denied", forbiddenDetail: "Your admin session is invalid. Please sign in again.", goToLogin: "Sign in"
    },
    api: { unauthorized: "Unauthorized", invalidOrigin: "Invalid request origin", jsonRequired: "JSON content type required", bodyTooLarge: "Request body is too large", invalidJson: "Invalid JSON", validationFailed: "Invalid settings", notFound: "Not found", serverError: "Server error", newPasswordEmpty: "New password cannot be empty", currentPasswordWrong: "Current password is incorrect", loginOrigin: "Could not verify the sign-in origin. Reload and try again.", loginTooLarge: "Sign-in data is too large.", loginFormat: "Invalid sign-in format.", passwordWrong: "Incorrect password." },
    icons: { globe: "Website", link: "Link", home: "Home", blog: "Article", rss: "RSS", code: "Code", book: "Book", briefcase: "Work", store: "Store", chain: "On-chain", email: "Email", phone: "Phone", message: "Message", calendar: "Calendar", map: "Map", camera: "Camera", cloud: "Cloud" }
  },
  ja: {
    contact: "連絡先", websites: "ウェブサイト", pending: "準備中", skip: "本文へ移動", notFound: "ページが見つかりません", back: "ホームに戻る", language: "言語", appearance: "表示設定", preferences: "サイトの表示設定", credit: "制作：", creditEnd: "", visitor: "人目の訪問者",
    admin: {
      title: "管理画面", description: "Contact Hub 管理画面", content: "コンテンツ管理", menu: "管理メニュー", profile: "プロフィール", bio: "自己紹介", links: "連絡先リンク", settings: "サイト設定", viewSite: "サイトを見る", logout: "ログアウト", save: "変更を保存",
      profileHelp: "公開する名前とステータスを設定します。", name: "名前", avatar: "アイコン画像", avatarHelp: "JPG・PNG・WebP をアップロードできます。自動でトリミング・圧縮します。", chooseImage: "画像を選ぶ", remove: "削除", imageUrl: "画像 URL（任意）", imageUrlHelp: "画像をアップロードするか、http(s) の画像 URL を入力してください。空欄なら名前の頭文字を表示します。", currentAvatar: "現在の画像", status: "ステータス",
      bioHelp: "訪問者向けの各言語で自己紹介を入力できます。", linksHelp: "連絡先の表示・順序を設定します。", addWebsite: "サイトを追加", addContact: "連絡先を追加", addEmail: "メールを追加", siteList: "ウェブサイト", contactList: "連絡先", displayName: "表示名", emailAddress: "メールアドレス", accountText: "アカウント／表示テキスト", url: "URL", icon: "アイコン", show: "表示", delete: "削除", deleteItem: "この項目を削除", moveUp: "上へ移動", moveDown: "下へ移動", order: "順番", unnamed: "名前なし", newLink: "新しいリンク", customUrl: "カスタム URL", maximumLinks: "連絡先リンクは最大 20 件です",
      settingsHelp: "ページタイトル、URL、ログインの安全設定を管理します。", siteTitle: "ブラウザーのタブ名", siteTitleHint: "空欄ならプロフィール名を使います。変更後は「変更を保存」を押してください。", canonical: "公開サイトの URL", canonicalHint: "検索・共有用の URL です。空欄なら現在のドメインを使います。", footerLink: "フッターのリンク", footerHelp: "名前か URL が空欄ならリンクを表示しません。", changePassword: "パスワードを変更", passwordHelp: "変更すると、すべての端末で再ログインが必要です。", currentPassword: "現在のパスワード", newPassword: "新しいパスワード", confirmPassword: "新しいパスワード（確認）", updatePassword: "パスワードを更新", updating: "更新中…", passwordMismatch: "新しいパスワードが一致しません", passwordUpdated: "パスワードを更新しました。再ログインしてください。", passwordUpdateFailed: "パスワードを更新できませんでした", saved: "保存しました", saveFailed: "保存できませんでした", imageType: "JPG・PNG・WebP のみ使用できます", imageFailed: "画像を処理できませんでした", imageUnreadable: "画像を読み込めませんでした", imageTooLarge: "圧縮後も画像が大きすぎます。別の画像を選んでください。", imageConvertFailed: "画像を変換できませんでした",
      loginPrompt: "管理者パスワードを入力してください。", password: "パスワード", signIn: "ログイン", backToSite: "連絡先ページに戻る", forbidden: "アクセスできません", forbiddenDetail: "管理セッションが無効です。再度ログインしてください。", goToLogin: "ログイン画面へ"
    },
    api: { unauthorized: "認証が必要です", invalidOrigin: "リクエスト元を確認できません", jsonRequired: "JSON 形式が必要です", bodyTooLarge: "リクエストが大きすぎます", invalidJson: "JSON 形式が正しくありません", validationFailed: "設定を確認してください", notFound: "見つかりません", serverError: "サーバーエラー", newPasswordEmpty: "新しいパスワードを入力してください", currentPasswordWrong: "現在のパスワードが違います", loginOrigin: "ログイン元を確認できません。再読み込みしてお試しください。", loginTooLarge: "ログインデータが大きすぎます。", loginFormat: "ログイン形式が正しくありません。", passwordWrong: "パスワードが違います。" },
    icons: { globe: "ウェブサイト", link: "リンク", home: "ホーム", blog: "記事", rss: "RSS", code: "コード", book: "本", briefcase: "仕事", store: "ショップ", chain: "オンチェーン", email: "メール", phone: "電話", message: "メッセージ", calendar: "カレンダー", map: "地図", camera: "カメラ", cloud: "クラウド" }
  }
};

export function uiFor(lang) { return UI[lang] || UI.en; }
